apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-xten
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/happy-path-service-tenant/appstudio/dc-metro-map-xten@sha256:ef8f099d734e700163e84891532a22ab3f50832c247e6c7ced53e869e735c5cf
        name: my-nodejs
        resources: {}
status: {}
